import AppRootLayout from "@/components/AppRootLayout";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppRootLayout>
      <div className="flex h-screen w-full">
        <div></div>

        <div className="w-full">
          <Header />
          <main className="mt-[68px]">{children}</main>
        </div>
      </div>
    </AppRootLayout>
  );
}
